- hosts: artix
  become: yes
  tasks:
  - name: Install packages
    community.general.pacman:
      name:
        - python
        - git
        - ansible
        - terraform
        - vim
        - kitty
        - discord
        - zathura
        - docker
        - docker-compose
      state: present

  - name: Clone dotfiles repo
    ansible.builtin.git:
      repo: https://github.com/barophobia/dotfiles
      dest: ~/dotfiles
  
  - name: Execute the shell install script
    command: "bash ~/dotfiles/linux/install.sh || /bin/true"
